-- 카테고리에 따라 게시글 조회

SELECT
       P.ID
     , P.TITLE
     , P.CATEGORY
     , P.UPLOAD_AT
     , P.UPDATE_AT
     , P.STATUS
     , P.MEMBER_ID
     , M.NICKNAME AS MEMBER_NICKNAME
  FROM POST P
  JOIN MEMBER M ON (P.MEMBER_ID = M.ID)
 WHERE P.CATEGORY = ?
 ORDER BY P.ID ASC;