-- 게시글 id로 사진 조회

SELECT
       PI.ID AS POST_IMAGE_ID
     , PI.IMAGE_PATH AS POST_IMAGE_PATH
     , PI.RENAMED_NAME AS POST_IMAGE_RENAMED_NAME
     , PI.IS_THUMBNAIL AS POST_IMAGE_IS_THUMBNAIL
  FROM POST_IMAGE PI
 WHERE PI.POST_ID = ?;