-- 현재 글에 맞는 댓글 조회

SELECT
       C.ID AS COMMENT_ID
     , C.IS_ADOPTED AS COMMENT_IS_ADOPTED
     , C.UPLOAD_AT AS COMMENT_UPLOAD_AT
     , C.UPDATE_AT AS COMMENT_UPDATE_AT
     , C.CONTENT AS COMMENT_CONTENT
     , C.STATUS AS COMMENT_STATUS
     , C.POST_ID AS COMMENT_POST_ID
     , C.ROOT_COMMENT_ID AS COMMENT_ROOT_COMMENT_ID
     , C.MEMBER_ID AS COMMENT_MEMBER_ID
     , CM.NICKNAME AS COMMENT_MEMBER_NICKNAME
  FROM COMMENT C
  JOIN MEMBER CM ON (C.MEMBER_ID = CM.ID)
 WHERE C.POST_ID = ?;